export const homeObjOne={
    id:'about',
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine:'Premium Bank',
    headline:'Unlimited transition with zero fees',
    description:'Get acces to our exlusive app that  allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel:'getStarted',
    imgStart:true,
    img: require('../../images/svg-1.svg'),
    alt:'Car',
    dark:true,
    primary:true,
    darkText:false,
}
export const homeObjTwo={
    id:'discover',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'Unlimited Access',
    headline:'Unlimited transition with zero fees',
    description:'Get acces to our exlusive app that  allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel:'Learn more',
    imgStart:true,
    img: require('../../images/svg-2.svg'),
    alt:'Car',
    dark:false,
    primary:false,
    darkText:true,
}
export const homeObjThree={
    id:'singup',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'Premium Bank',
    headline:'Unlimited transition with zero fees',
    description:'Get acces to our exlusive app that  allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel:'Start now',
    imgStart:false,
    img: require('../../images/svg-3.svg'),
    alt:'Car',
    dark:false,
    primary:false ,
    darkText:true,
}
export const homeObjFour={
    id:'about',
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine:'Premium Bank',
    headline:'Unlimited transition with zero fees',
    description:'Get acces to our exlusive app that  allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel:'getStarted',
    imgStart:true,
    img: require('../../images/svg-4.svg'),
    alt:'Car',
    dark:true,
    primary:true,
    darkText:false,
}
export const homeObjFive={
    id:'discover',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'Unlimited Access',
    headline:'Unlimited transition with zero fees',
    description:'Get acces to our exlusive app that  allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel:'Learn more',
    imgStart:true,
    img: require('../../images/svg-5.svg'),
    alt:'Car',
    dark:false,
    primary:false,
    darkText:true,
}
export const homeObjSix={
    id:'singup',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'Premium Bank',
    headline:'Unlimited transition with zero fees',
    description:'Get acces to our exlusive app that  allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel:'Start now',
    imgStart:false,
    img: require('../../images/svg-3.svg'),
    alt:'Car',
    dark:false,
    primary:false ,
    darkText:true,
}